import React from 'react';

export const characters = [
    {
        header: 'Introduction',
        title: 'This is You',
        photo: '4.jpg',
        position: { x: 150, y: 200 },
        content: <div>
            <p>Hello, if you&rsquo;ve just made it to this part of the journey there are probably a lot of questions, you&rsquo;re asking yourself right now such as: </p>
            <p>1. What is this? </p>
            <p>2. What&rsquo;s it&rsquo;s point? </p>
            <p>3. Who is No.4? </p>
            <p>Since this is the shortest to answer, I&rsquo;ll start with the ladder: No.4 is you, and who you are to the other characters on this page. Really, your name isn&rsquo;t all that special. You have four freckles and you got to be No.4 because of it! </p>
            <p>Now, I should answer the other two: What is this? Well, unfortunately one way or another you have found yourself dead centre in what will be coined on this expedition as &lsquo;The Male Social Hierarchy&rsquo;. Simply put, <strong>&lsquo;The Male Social Hierarchy&rsquo;</strong> can be defined as a way human beings, in this case fictional upper class white men, organize themselves to create a sense of security through their unity. The Male Social Hierarchy stems from organizational patterns studied by scholars, mainly psychologists and philosophers, who believe that men form themselves within this hierarchy through displays of their status. The ones who are the best at establishing their <strong>masculine identity</strong> in a <strong>collaborative manner</strong> that is <strong>accepted</strong> by those beneath them on the hierarchy are the ones who will find their position at the top (Flood, 2008, 339). Often, the establishment of this function described as being done through men&rsquo;s sexual prowess but really, any factor that allows men to re-establish their masculinity can have this function. No.4, you are in the middle of the hierarchy. Not too great, but not to terrible either. If it&rsquo;s any condolence, at least you&rsquo;re not at the bottom, right? </p>
            <p> There are two, rather infamous, Male Social Hierarchies that best describes what happens when this social order is established; the Choir Boys from William Goulding&rsquo;s &lsquo;<em>Lord of The Flies</em>&rsquo; and The Suitors from <em>Homers Odyssey.</em> Both these groups have a lot in common; they were written about <strong>after major wars</strong>, both are <strong>upper-class</strong>, practically <strong>isolated on an island</strong>, choose specific people to <strong>leave out</strong> of their hierarchy and, lastly, thrive off violence. The list of traits these two groups have in common once their social hierarchy is established can go on for a while. Additionally, No.4, both these groups are meant to represent you and your hierarchy. What will we uncover together on this journey is what factors make &lsquo;The Male Social Hierarchy&rsquo; end up this way? And what does this mean for people outside of the fictional realm? In this study, we will explore the <strong>choices</strong> of the individual, the purpose of <strong>unity</strong>, and the influence of the elites as factors that form The Male Social Hierarchy. <strong>Through these spheres, we will discuss the factors which shape The Male Social Hierarchy are the adoption of Dionysian behavior, establishment of group mentality, and the influence from The Elites. These factors combined allow The Hierarchy to form with the traits that are seen through the men in <em>Homers Odyssey </em>and<em> Lord of The Flies. </em>&nbsp;</strong> </p>

        </div>
    },
    {
        header: 'On the Outskirts Part 1',
        title: 'The Willing Outlier',
        photo: 'outlier.jpg',
        position: { x: 200, y: 300 },
        content: <div>
            <p>First, let&rsquo;s look at the bottom of The Male Social Hierarchy: There are different ways that characters can end up in this position but what they have in common, is that theology can explain how they got there. When looking at the bottom of the hierarchy, there are many differences between these characters. Some <strong>willingly distinguish themselves</strong> from the rest of the group despite their physical and mental capabilities, some are there for a <strong>lack of one of those two traits</strong> and some are <strong>pushed into this role</strong>. What separates these characters from the others is their ability to maintain their <strong>civil behavior and attitudes</strong>. Let&rsquo;s look first at &lsquo;The Willing Outlier&rsquo;:</p>
            <p>No.4, remember on the last page how I mentioned that you are somewhere in the middle of the hierarchy and essentially, unimportant? Well, unlike you The Willing Outlier <em>is</em> important, possibly even the most important in the entire hierarchy. Therefore, he is represented by the protagonists of both these stories like Ralph in <em>Lord of the Flies</em> and Odysseus in <em>The</em> <em>Odyssey</em>. These characters have two important traits in common: their equal, if not greater, abilities to the leader of the hierarchy and their ability to maintain civil behavior. To expand: </p>
            <p>At the end of both works, Odysseus and Ralph are pitted against their peers. Ralph is shown fighting the leader of his hierarchy, Jack, before a soldier comes and stops them which ultimately saves the boys (Golding, 1953, 287). Furthermore, Odysseus defeats the suitors, the main social hierarchy in this analysis, but since most of these characters are younger than him, they cannot be considered his peers, meaning the fighting is not considered equal (Hom.Od.22.285-90). When the suitors&rsquo; parents, who <em>would be his peers</em> confront him, the fight is stopped by Athena who wipes their memories (Ibid, 24.545-550). This phenomenon is explained best with <strong>Nietzsche&rsquo;s Apollonian-Dionysian Theory</strong>: What this discusses is the internal conflict between one&rsquo;s civilized and uncivilized traits that all humans possess (Carlevale, 2006, 364). If one gives way to the uncivilized side, they form a violent, hostile union like the Male Social Hierarchy. If one holds onto logic, reason, and their civilized aspects, they reject the formation of the hierarchy itself an become an outlier (Gleason, 2002, 9). Therefore, Ralph and Odysseus are representative of the &lsquo;purest&rsquo; form of Nietzsche&rsquo;s ideals since they choose the &lsquo;Apollonian&rsquo;, orderly, side of his view rather than the &lsquo;Dionysian&rsquo;, disorderly, views despite their obvious abilities to be leaders. </p>
            <p> This information communicates that those at the bottom of the &lsquo;Male Social Hierarchy&rsquo; work to maintain conventional societal order and rather, create an order in &lsquo;Apollonian terms&rsquo; </p>
        </div>
    },
    {
        header: 'On the Outskirts Part 2',
        title: 'The Brain',
        photo: 'brain.jpg',
        position: { x: 100, y: 300 },
        content: <div>
            <p>Alright, now that we&rsquo;ve covered the high-and-mighty Willing Outlier, let&rsquo;s look at The Brain. While The Brain still makes the active decision to choose their &lsquo;Apollonian&rsquo; side over the Dionysian one, they are somewhat more restricted to this role. Unlike The Willing Outlier, they lack in certain physical capabilities that prohibit their means to have the abilities to ever be fully included within the hierarchy. For &lsquo;Piggy&rsquo; from <em>Lord of The Flies</em> and Telemachus from <em>The Odyssey,</em> their weaknesses fall on their lack of physical capabilities. For example, this is an evident flaw for &lsquo;Piggy&rsquo; as his weight was even the origin of his nickname which is the only title the reader ever receives for him (Golding, 1953,12). In comparison, Telemachus is bullied by the other suitors for his inability to live up to his father&rsquo;s stature (Hom.Od.2.40-65). Even so, Piggy is still <strong>intelligent</strong> enough to advise Ralph when making important decisions (Golding, 1953, 290). Additionally, Telemachus is under the watch of Athena, meaning that he may not have his father&rsquo;s strength but possesses the same intelligence (Hom.Od.2.405-6). </p>
            <p>This means that The Brain is not a member of the hierarchy who is one of the strongest, but based on their intelligence, not fully incapable of proving themselves to the other members who are better established within the group. Therefore, Nietzsche&rsquo;s Apollonian-Dionysian theory can only be partially attributed to these characters since in his theory, he discusses how their choices to be civilized are <strong>done consciously</strong> (Carlevale, 2006, 384). Therefore, one must look at these characters motives for finding themselves at the bottom of the hierarchy. Scholars, Karen May and David Upton describe that characters such as Piggy and Telemachus attach themselves to The Willing Outliers in order to survive the hierarchy itself (May and Upton, 2015, 71). Their lack of physical abilities and heightened intelligence make them subversive to the &lsquo;Dionysian&rsquo; actions that less intelligent, and more physically capable characters would be more susceptible too but they cannot defend themselves the way The Willing Outlier can. Therefore, though these characters make an intellectual decision to stay outside of the hierarchy, they are still reliant on The Willing Outlier to give them security in that position. Therefore, one can deduce that there is not a strong emphasis on intellectual skills in these Male Social Hierarchy and have a greater emphasis on physical strength. </p>
        </div>
    },
    {
        header: 'On the Outskirts Part 3',
        title: 'No.0',
        photo: '0.jpg',
        position: { x: 0, y: 300 },
        content: <div>
            <p>Okay No.4, this is the first <em>actual</em> member of your cohort, No.0; you and your other peers agreed on not giving him a proper number because he isn&rsquo;t particularly deserving of it. Afterall, No.0 is definitely <strong>the weak link</strong> of the group; he isn&rsquo;t the sharpest knife in the toolbox, and honestly, not that physically capable either. Nonetheless, he&rsquo;s here with your group now so there isn&rsquo;t much you can do about it. Not to mention, he get&rsquo;s along with the other two outcasts well which doesn&rsquo;t help much with his reputation. </p>
            <p> If he were to be compared to any two characters, it would be Simon from <em>Lord of The Flies</em> and Amphinomus from <em>The Odyssey</em>. These characters represent the situation members of The Male Social Hierarchy are trapped in when they find themselves the least capable of the entire group. They can be adopted by The Outcasts, such as Simon when he is shown looking up to and relying on Ralph and when Odysseus warns Amphinomus of the massacre that will pursue (Golding, 1953, 92; Hom.Od.18.145-9). Though this is helpful to them, both these characters end <strong>up dying</strong> at the end of their respective stories (Golding, 1953, 224; Hom.Od.22.90-4). This demonstrates that without the support of brains or brawn, as mentioned earlier, these individuals could not be successful within The Male Social Hierarchy and are <strong>rejected </strong>because of it (Zink et.al, 2008, 273). Even so, both these characters still align themselves with Apollonian thought since they show acts of kindness to the other characters (Carlevale, 2006, 367). This phenomenon can be described best as No.0 adopting Apollonian behavior in a non-Nietzschean manner since the decision cannot be made willingly. </p>
            <p> In all, the factor that contributes to the outliers are their physical and mental abilities as well as the characters alignment with &lsquo;civilized&rsquo; or pacifistic tendencies that separate them from the rest of the group. If they cannot defend themselves, they are on the outskirts by default which is separate from those who do so willingly. By joining The Outliers, one has to adopt an <strong>Apollonian set of values</strong> no matter what their reason for it may be. </p>
        </div>
    },
    {
        header: 'Family Part 1',
        title: 'No. 5',
        photo: '5.jpg',
        position: { x: 50, y: 200 },
        content: <div>
            <p>Now that we&rsquo;ve looked at the bottom of the hierarchy, it is time to discuss your equals No.4. Some of them may be better than you in some ways, maybe you&rsquo;re better than them in others but overall, you are all basically on the same level. Additionally, as part of the body of the hierarchy, they lack less personality than those above and below since their role is to <strong>follow</strong>. If you were to be compared to any character in <em>Lord of The Flies</em> or <em>Homers Odyssey</em>, you would be one of the background characters. This would include Sam and Eric from <em>Lord of The Flies</em> or any of the random suitors, such as Elatus or Ctesippus, from <em>The Odyssey</em>. These characters are acknowledged within the story but ultimately unimportant to the plot as individuals. Where their function truly lies is in their &lsquo;character&rsquo; as a unit. It highlights the mentality that allows The Male Social Hierarchy to form as well as the post war backing that shaped both these stories. </p>
            <p>No.5 is another member of the group and to a certain extent, one of your competitors. Scholar Ruth Scodel applies a model known as <strong>Game Theory</strong> to the interactions of the Suitors from <em>Homers Odyssey</em>. Game Theory involves the idea that goals are achieved among the greater collective of The Male Social Hierarchy when they view one another as competition where a winner may appear (Scodel, 2001, 308). In the case of the Suitors from <em>The Odyssey</em>, the central &lsquo;game&rsquo; that they play revolves around who can marry Penelope, Odysseus&rsquo;s wife, and through this, claim the entire kingdom (Hom.Od.1.332). This idea of Game Theory is also extended to <em>Lord of The Flies</em> since their task of survival is ultimately treated like a game to engage the younger children of the story (Golding, 1953, 47). Without the use of Game Theory, these groups would not be able to function and establish one&rsquo;s place within the social hierarchy. This is directly related to the importance of one&rsquo;s physical capabilities in the games, as mentioned in the previous section, since many of their tasks require physical effort to complete. Some examples of this are the boy&rsquo;s emphasis on hunting pigs in <em>Lord of the Flies </em>and the suitors show of archery at the end of <em>The Odyssey</em> (Golding, 1953, 44; Hom.Od.21.79-82). </p>
            <p>Therefore, the use of Game Theory in The Male Social hierarchy unites those who are in the &lsquo;middle&rsquo; of the game and establishes everyone&rsquo;s <strong>rank</strong> among one another. Without the aspect of Game Theory in the hierarchy, the group would not be able to function since they would have no common motive. </p>
        </div>
    },
    {
        header: 'Family Part 2',
        title: 'No.3',
        photo: '3.jpg',
        position: { x: 250, y: 200 },
        content: <div>
            <p>Both <em>Lord of the Flies</em> and <em>Homers Odyssey</em> function in the real world as a coping mechanism for individuals emerging into a post-war era. <em>Lord of The Flies</em> was released after the Second World War and <em>The Odyssey</em> emerged after the Peloponnesian war (Van Vurren, 2004; Palagia, 2009, 35). Both these conflicts were major and changed the states attitude towards society which manifested itself in this fiction, England, and Ancient Greece, in ways that could not be reversed. Furthermore, although Homers identity is unknown to contemporary scholars, William Goulding was known for his pessimistic outlook on how a society heals after war (Van Vuuren, 2004) . Since The Male Social Hierarchy functions in the same manner for both, it can be deduced that the outlook of the story was interpreted in similar ways. Afterall, the suitors come from the generation after Odysseus and, therefore, after the Trojan War was which was mentioned in the Illiad. By having a <strong>&lsquo;war-like&rsquo; mentality</strong> without any immediate threat to face, aggressive and violent attitudes manifest within the Suitors and the Choir Boys. No.4, you, No.3 and the rest of your family are in the middle of the pack and fight your own made-up problems as well. </p>
            <p>For example, the Suitors &lsquo;war&rsquo; that they fight is their pursuit of Penelope. Although they look to marry her, they still treat her as a threat and therefore want to weaken her. This is shown when they realize that the tapestry, she was making functioned to stall The Suitors from forcing her to choose one of them to marry (Hom.Od.2.111-6). From here, The Suitors attempt to &lsquo;defeat&rsquo; Penelope by threatening to murder her son, Telemachus. In <em>Lord of The Flies</em>, the boys &lsquo;enemy in battle&rsquo; is The Beast, a creature that doesn&rsquo;t exist, yet they are all still determined to hunt down. When The Beast is murdered and revealed to be Simon who the boys killed, they can only unleash their violence on one another, holding onto their war mindset now with no direction (Van Vurren, 2004). </p>
            <p>Though these actions still function as an aspect of &lsquo;Game Theory&rsquo; the violence behind them is what demonstrates their war-like mentality. What begins as a challenge between members of the hierarchy quickly divulge into a formation where the men find an opponent to fight to establish their unity but also find a level of safety through it. Therefore, characters who cannot provide any support or safety, like Telemachus and Simon, are removed by the other members to maintain their strength as a group against future threats. In all, it is inferred that this behavior evolves out of the fear of conflict with no direct threats to face. </p>
        </div>
    },
    {
        header: 'Family Part 3',
        title: 'No.2',
        photo: '2.jpg',
        position: { x: 350, y: 200 },
        content: <div>
            <p>No.4, I&rsquo;m sure you have some questions about these people titled your &lsquo;so-called-family&rsquo;, they&rsquo;re violent and competitive with one another and don&rsquo;t seem to have much genuine compassion for each other. So, what is it that makes you guys&rsquo; family? Let&rsquo;s look back to the idea of &lsquo;war mentality&rsquo;; you all consider each other a cohort because it works to be a means of <strong>survival</strong>. In other words, you, No.2 and the others are a family because otherwise, you risk the dangers of being on the outskirts. </p>
            <p>Both Jack, the leader of The Choir Boys, and Antinous, leader of The Suitors, both make the effort to kill those who are on the outskirts. Jack tries to kill Ralph himself at the end of the novel and incites the murder of Simon under the impression that he is &lsquo;the beast&rsquo;(Golding, 1953, 290). Furthermore, Antinous attempts to murder both Telemachus and Odysseus but is unsuccessful on both fronts (Hom.Od.2.330-7, 22.27-33). Note that in both these situations, they are fully supported by the &lsquo;family&rsquo; of the social hierarchy without question when these acts are committed. This functions to demonstrate how the &lsquo;games&rsquo; the two groups create for themselves further their war-like mentality but re-establish who is &lsquo;in&rsquo; the group and who is not. How the men continue to function in this manner despite there being no emotional connection between one another is described best by Daniel Levine: </p>
            <p>Levine focuses on The Suitor&rsquo;s lack of genuine emotion depicted throughout <em>The Odyssey</em>. Specifically, he pays careful attention to the depictions of their <strong>laughter</strong>. Here, he describes that the laughter The Suitors demonstrate is not to show joy or humor at a particular event but rather to demonstrate their group solidarity in a situation (Levine, 1982, 98). When leaders of the hierarchy demonstrate their laughter individually, it reaffirms their status since they function independently. Additionally, Levine explains that the laughter is used in a &lsquo;militant&rsquo; manner allowing characters to utilize laughter as a &lsquo;battle cry&rsquo; before entering turbulent situations. Therefore, they are seen mainly laughing around Penelope since she is a threat to them (Ibid). In comparison, The Choir Boys express their &lsquo;laughter&rsquo; in a more overt manner by using &lsquo;play&rsquo;. When they describe themselves as a tribe, with battle paint and chants, they re-enforce their group unity in the same manner with Jack as their leader since many of these ideas were his (Golding, 1953, 28). </p>
            <p>In all, the use of the &lsquo;family&rsquo;s&rsquo; implementation of &lsquo;Game Theory&rsquo;, battle laughter and their militant unity help define the members of their group and create practices that define them as a <strong>singular unit</strong> rather than a combination of many individuals. No.4, you don&rsquo;t need a name greatly different from your cohorts since you are, in essence, exactly like them. </p>
        </div>
    },
    {
        header: 'The Elites Part 1',
        title: 'No.1',
        photo: '1.jpg',
        position: { x: 450, y: 200 },
        content: <div>
            <p>Here we are No.4, making it to the top now. In this final section we&rsquo;ll explore how these characters have managed to establish their status within the Male Social Hierarchy and what factors allow them to be perceived this way. Furthermore, we will mainly be discussing this through the lens of power what traits give this influence in the first place. To expand, both <em>The Odyssey </em>and <em>Lord of The Flies</em> establish the dynamic of power using delicate techniques that are not always obvious upon a first read. What makes you, No.4, different from No.1? He is not that much higher than you on the Hierarchy, but he is not fully one of The Elites either. The answer? No.1 doesn&rsquo;t have <strong>the means to establish power</strong> whereas the other two do. Creating this sense of authority is shown through symbolism, mainly pigs, and how the two top elites use <strong>normalization of Dionysian values</strong> and <strong>charisma</strong> to influence the rest of The Family. In other words, what makes No.1 separate from these other two is he has no means to influence the others even if he is higher ranking. </p>
            <p>&nbsp;Stephanie Jamison describes the use of pigs in <em>The Odyssey</em> to allude to the concept of <strong>kingship</strong>, which explains why Odysseus takes refuge with the swineherd in the epic (Jamison, 1999, 263). Additionally, it is described that The Suitors have eaten most of the pigs throughout the duration of <em>The Odyssey</em> more than any of the other animals. This demonstrates how the use of pigs represents The Suitors control of the kingdom (Ibid). The same concept can be translated to <em>Lord of The Flies</em> since pigs are the central animals the boy&rsquo;s hunt. The leaders of the hunt, such as Jack, claim their elite position over the rest of the hierarchy by hunting these animals. Characters like Antinous, the leader of The Suitors, and Jack are the ones to encourage the hunt, which furthers their association with this royal symbol and continues their place at the top of the hierarchy. The killing of pigs also acts as a symbol to <strong>overturn the pre-existing elite structures</strong> that were in place before the establishment of The Male Social Hierarchy. By killing the pigs, they are also killing Ralph and Odysseus&rsquo;s role as an elite actor before the killing of the of the pigs and therefore, the current status quo. This idea is confirmed by the swineherd discussing how pigs were killed in moderation under Odysseus&rsquo;s rule and when Ralph suggests picking fruit and building shelter over hunting (Hom.Od.14.80-8; Golding, 1953, 50) By the elites turning their focus on hunting pigs form former goals, they erase the pre-existing power structure. </p>
            <p>In all, the use of pigs in both these stories act to establish the change of power and works to build who would be considered the elites within the male social hierarchy. </p>
        </div>
    },
    {
        header: 'The Elites Part 2',
        title: 'The Eye',
        photo: 'eye.jpg',
        position: { x: 250, y: 100 },
        content: <div>
            <p>Arguably, The Eye can be seen as one of the most crucial members in forming The Male Social Hierarchy. While The King, who we&rsquo;ll discuss later, delegates the tasks for The Family, The Eye is the one who normalizes this Dionysian behavior that The Family follows. Normally, this aspect is demonstrated through The Eye&rsquo;s extreme demonstration of the expectations The King establishes for the rest of The Family to follow. The Eye does this in a manner where the rest of the members beneath him only need to be a fraction as extreme, which <strong>encourages indoctrination</strong> into the group.</p>
            <p>The characters from <em>Lord of The Flies</em> and <em>Homers Odyssey</em> that best represent The Eye are, respectively, Rodger and Eurymachus. For most of the story, Rodger acts as Jack&rsquo;s henchman but goes above and beyond in following his orders. There are two prominent examples of this; his extremely violent killing of a female pig and being the one to push the rock that ultimately kills Piggy (Golding, 1953, 276). Eurymachus demonstrates the same extreme behavior when he throws a stool at Odysseus in disguise, an act that is considered violent even to the other Suitors (Hom.Od.18.395). By doing this, these actions encourage the other members of their cohorts to attempt the same behavior. This is shown through the other Choir Boys joining in on the killing of the pig and The Suitors laughing at the stool being thrown at Odysseus (Golding, 1953, 192-6; Hom.Od.18.397ff). Rifaat Salih describes &lsquo;The Eye&rsquo; as characters that are the least connected to their civilized roots, even more than The King (Rifaat, 2019, 42). Therefore, this character functions as the <strong>establishing factor of Dionysian views</strong> since they are less focused on being charismatic, which is inherently Apollonian and the role adopted by The King. </p>
            <p>Without the implementation of The Eye, there is no-one to encourage and oversee the actions of the rest of The Family. Additionally, their violence towards The Outsiders re-establishes their place as the most uncivilized and confirms who is and is not allowed within the family. </p>

        </div>
    },
    {
        header: 'The Elites Part 3',
        title: 'The King',
        photo: 'king.jpg',
        position: { x: 150, y: 0 },
        content: <div>
           	<p>Here we are No.4, at the top of The Male Social Hierarchy, The King. The King was not always in this position as he had taken the power from the other characters beneath him. Mainly, this involved taking the power from The Willing Outlier. Though they may not encourage all the actions of those beneath him, which is attributed to The Eye, they remain at the top since they invent the Dionysian tasks in the first place. Despite the uncivilised actions The King may adopt, he is not completely removed from his civilized side. He is more charismatic and manipulative than those beneath him and also exhibits strong athletic abilities. His charisma and talents are the factors which invite the other members of The Male Social Hierarchy to follow him and therefore, allot the most power to the character. </p>
            <p>Antinous, from <em>The Odyssey</em>, and Jack, from <em>Lord of The Flies</em>, are the members who take this role. They are the ones that form the hierarchy after taking the power away from The Willing Outliers. This is shown when Antinous is described as the most likely to court Penelope and when Jack introduces the idea of the hunt (Hom.Od.18-285-290; Golding, 1953,47). When these characters come to power, they introduce the &lsquo;battle mentality&rsquo; that the rest of The Family adopts. This demonstrates his show of charisma since none of the other suitors are seen making romantic gestures such as this towards her to achieve the same goal. One example of this is when Antinous is shown being the first member of the group to put down Telemachus when he speaks up against the suitors which the others quickly join in (Hom.Od.1.381-8).By being the first to outcast Telemachus at the beginning of the Epic, he is established as the &lsquo;winner&rsquo; of their collective battle task and the most socially capable of The Suitors. Furthermore, by being the first to speak, Antinous is also presented at the top of the &ldquo;proper order&rdquo;, which references the Male Social Hierarchy, demonstrates that he is the leader of the group (Ibid, 1.145). Additionally, he is also one of the few characters to laugh on his own without the influence of the rest of the group, furthering the example of his social capacity in establishing dominance. Jack also displays these traits by placing emphasis on the boys &lsquo;fun&rsquo; rather than completing tasks that would be beneficial to their survival such as building huts. This influences the other Choir Boys into following him throughout the rest of the story (Golding, 1953, 47). Therefore, one can deduce that the use of charisma places &lsquo;The King&rsquo; at the top of the hierarchy and creates the greatest influence over the rest of the characters. </p>
            <p>Therefore, we can see that characters at the top of the male Social Hierarchy through their establishment of royal connotations, leadership in social situations and normalization of behavior to the other characters. </p>
        </div>
    },
    {
        header: 'Conclusion',
        title: 'The Universal Empire',
        photo: '',
        position: { x: -Number.MAX_SAFE_INTEGER, y: -Number.MAX_SAFE_INTEGER },
        content: <div>
            <p>That&rsquo;s it No.4, The Male Social Hierarchy: </p>
            <p>From this information, there are three factors which define this group, the adoption of Dionysian behavior, establishment of group mentality, and the influence from The Elites. There is only one question that remains: what&rsquo;s the point? How can this information apply to anything feasible? </p>
            <p>Both the stories used throughout this project are influential for a reason; even if they cannot describe real people, they are prime examples of the thoughts and concerns that people have within their society at the time the story was written. No.4, when this journey comes to an end, I encourage you too look at how fiction functions in your everyday life and what the stories you consume represent the rest of our world. Ask yourself the question, how does this effect our lives now? Additionally, what aspects from <em>Lord of The Flies </em>or <em>Homers Odyssey </em>are applicable to contemporary life? If you ever get the opportunity to leave the Male Social Hierarchy, weather it be by miraculous soldier breaking up a fight or Athena brainwashing your foes, challenge yourself to look at how this social structure represents real life social pressures or concerns. </p>
            <p>Now, on your way No.4, you don&rsquo;t want The King to think you can&rsquo;t keep up with the others!</p>
        </div>
    }
];